apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-mysql-ops-operations
  namespace: argo
spec:
  templates:
  - name: run-query
    inputs:
      parameters:
      - name: connection-string
        # Format: host:port/database:user@password
      - name: query
    container:
      image: argo-mysql-ops-combined:latest
      command: ["/app/scripts/run-query.sh"]
      args: ["{{inputs.parameters.connection-string}}", "{{inputs.parameters.query}}"]
