apiVersion: v1
kind: ServiceAccount
metadata:
  name: operate-workflow-sa
  namespace: argo-events
---
# in order for the sensor to be able to create workflows in the argo namespace,
# we need to create a Role in the argo namespace (where workflows are created)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
  namespace: argo  # This Role is in the argo namespace where workflows are created
rules:
  # Allow sensor to create workflows
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
  # Allow sensor to read workflowtemplates
  - apiGroups:
    - argoproj.io
    resources:
    - workflowtemplates
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
  namespace: argo  # RoleBinding is in the namespace where access is needed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo-events  # SA is from argo-events namespace